version: '3.5'
services:
  clickhouse:
    image: dizballanze/clickhouse:1.1.54370
    volumes:
    - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
    #- "./data/clickhouse/data:/var/lib/clickhouse/data"
    #- "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"
    networks:
    - default

  clickhouse-init:
    image: dizballanze/clickhouse:1.1.54370
    volumes:
    - "./init.sql:/init.sql"
    entrypoint: |
      bash -c '
        sleep 5
        export HOME=/var/lib/clickhouse/
        cat /init.sql | clickhouse client --host clickhouse --multiquery'
    networks:
    - default

  carbon-clickhouse:
    image: mosquito/carbon-clickhouse
    #volumes:
    #- "./data/carbon-clickhouse:/data/carbon-clickhouse/data"
    #- "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
    ports:
    - "2003:2003" # plain tcp
    - "2003:2003/udp" # plain udp
    - "2004:2004" # pickle
    networks:
    - default
    environment:
      CLICKHOUSE_URL: http://clickhouse:8123/
      CLICKHOUSE_DATA_TABLE: graphite.data
      CLICKHOUSE_TREE_TABLE: graphite.metrics
      DATA_CHUNK_INTERVAL: 30s
      DATA_CHUNK_AUTO_INTERVAL: "5:10s,20:60s,100:600s"

  graphite-clickhouse:
    image: graphite-clickhouse:latest
    volumes:
    - "./graphite-rollup.xml:/etc/graphite-clickhouse/rollup.xml"
    - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
    networks:
    - default
    environment:
      CLICKHOUSE_URL: http://clickhouse:8123/
      CLICKHOUSE_DATA_TABLE: graphite.data
      CLICKHOUSE_TREE_TABLE: graphite.metrics
      COMMON_MAX_CPU: 2
      COMMON_KEEP_DUPLICATES: "true"

  carbonapi:
    image: openmetric/carbonapi
    volumes:
    - "./carbonapi.yaml:/etc/carbonapi.yaml"
    entrypoint: |
      sh -c 'carbonapi -config /etc/carbonapi.yaml'
    ports:
    - "80:80"
    networks:
    - default

  grafana:
    image: grafana/grafana:5.2.3
    volumes:
    - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
    - "./grafana/provisioning:/etc/grafana/provisioning"
    - "./grafana/graphite-clickhouse.json:/var/lib/grafana/dashboards/graphite-clickhouse.json"
    ports:
    - "3000:3000"
    networks:
    - default

networks:
  default:
